# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "yokigo"
license = "MIT"
licenselink = "https://github.com/arsalan86/yoki-go/blob/LICENSE"
description = "Minimal blog theme for hugo based on hucore"
homepage = "https://github.com/arsalan86/yoki-go/"
tags = ["blog", "font awesome", "highlight.js"]
features = ["html5", "css3", "tags"]
min_version = 0.16

[author]
  name = "Arsalan Pirzada"
  homepage = "https://www.arsalanpirazada.com/"